from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(640, 297)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.id_lbl = QLabel(self.centralwidget)
        self.id_lbl.setObjectName(u"id_lbl")
        self.id_lbl.setGeometry(QRect(20, 10, 63, 30))
        font = QFont()
        font.setFamily(u"\ub9d1\uc740 \uace0\ub515")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.id_lbl.setFont(font)
        self.pw_lbl = QLabel(self.centralwidget)
        self.pw_lbl.setObjectName(u"pw_lbl")
        self.pw_lbl.setGeometry(QRect(20, 50, 84, 30))
        self.pw_lbl.setFont(font)
        self.url_lbl = QLabel(self.centralwidget)
        self.url_lbl.setObjectName(u"url_lbl")
        self.url_lbl.setGeometry(QRect(20, 120, 42, 30))
        self.url_lbl.setFont(font)
        self.date_lbl = QLabel(self.centralwidget)
        self.date_lbl.setObjectName(u"date_lbl")
        self.date_lbl.setGeometry(QRect(20, 160, 42, 30))
        self.date_lbl.setFont(font)
        self.file_lbl = QLabel(self.centralwidget)
        self.file_lbl.setObjectName(u"file_lbl")
        self.file_lbl.setGeometry(QRect(20, 200, 42, 30))
        self.file_lbl.setFont(font)
        self.id_edt = QLineEdit(self.centralwidget)
        self.id_edt.setObjectName(u"id_edt")
        self.id_edt.setGeometry(QRect(120, 10, 381, 36))
        self.id_edt.setFont(font)
        self.pw_edt = QLineEdit(self.centralwidget)
        self.pw_edt.setObjectName(u"pw_edt")
        self.pw_edt.setGeometry(QRect(120, 50, 381, 36))
        self.pw_edt.setFont(font)
        self.url_edt = QLineEdit(self.centralwidget)
        self.url_edt.setObjectName(u"url_edt")
        self.url_edt.setGeometry(QRect(120, 120, 431, 36))
        self.url_edt.setFont(font)
        self.file_edt = QLineEdit(self.centralwidget)
        self.file_edt.setObjectName(u"file_edt")
        self.file_edt.setGeometry(QRect(120, 200, 431, 36))
        self.file_edt.setFont(font)
        self.date_edt = QDateEdit(self.centralwidget)
        self.date_edt.setDisplayFormat("yyyy-MM")
        self.date_edt.setObjectName(u"date_edt")
        self.date_edt.setGeometry(QRect(120, 160, 431, 36))
        self.date_edt.setFont(font)
        self.file_btn = QPushButton(self.centralwidget)
        self.file_btn.setObjectName(u"file_btn")
        self.file_btn.setGeometry(QRect(560, 200, 36, 36))
        font1 = QFont()
        font1.setFamily(u"Agency FB")
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setWeight(75)
        self.file_btn.setFont(font1)
        self.confirm_btn = QPushButton(self.centralwidget)
        self.confirm_btn.setObjectName(u"confirm_btn")
        self.confirm_btn.setGeometry(QRect(500, 250, 125, 38))
        self.confirm_btn.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\ubed1\ud0b9 \uc6f9 \ud06c\ub864\ub7ec_ver.2", None))
        self.id_lbl.setText(QCoreApplication.translate("MainWindow", u"\uc544\uc774\ub514", None))
        self.pw_lbl.setText(QCoreApplication.translate("MainWindow", u"\ud328\uc2a4\uc6cc\ub4dc", None))
        self.url_lbl.setText(QCoreApplication.translate("MainWindow", u"\uc8fc\uc18c", None))
        self.date_lbl.setText(QCoreApplication.translate("MainWindow", u"\ub0a0\uc9dc", None))
        self.file_lbl.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c", None))
        self.file_btn.setText(QCoreApplication.translate("MainWindow", u"\u25b2", None))
        self.confirm_btn.setText(QCoreApplication.translate("MainWindow", u"\ud655 \uc778", None))
    # retranslateUi

